{
 "title": "Memory",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": "SELECT DISTINCT node FROM node ORDER BY node ASC;"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Memory",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT total FROM memory LIMIT 50 "
    },
    {}
   ]
  },
  {
   "title": "Free Memory",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT free FROM memory LIMIT 50 "
    },
    {}
   ]
  },
  {
   "title": "ERTS Allocators",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 14, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(ts),\n  ebinary\nFROM\n  ertsalloc\nWHERE\n (ts BETWEEN $__timeFrom() AND $__timeTo()) AND \n  node='[[node]]'\nORDER BY ts"
    },
    {
     "rawSql": "SELECT\n  $__time(ts),\n  driver\nFROM\n  ertsalloc\nWHERE\n (ts BETWEEN $__timeFrom() AND $__timeTo()) AND \n  node='[[node]]'\nORDER BY ts"
    },
    {
     "rawSql": "SELECT\n  $__time(ts),\n  eheap\nFROM\n  ertsalloc\nWHERE\n (ts BETWEEN $__timeFrom() AND $__timeTo()) AND \n  node='[[node]]'\nORDER BY ts"
    },
    {
     "rawSql": "SELECT\n  $__time(ts),\n  ets\nFROM\n  ertsalloc\nWHERE\n (ts BETWEEN $__timeFrom() AND $__timeTo()) AND \n  node='[[node]]'\nORDER BY ts"
    },
    {
     "rawSql": "SELECT\n  $__time(ts),\n  ll\nFROM\n  ertsalloc\nWHERE\n (ts BETWEEN $__timeFrom() AND $__timeTo()) AND \n  node='[[node]]'\nORDER BY ts"
    },
    {
     "rawSql": "SELECT\n  $__time(ts),\n  sl\nFROM\n  ertsalloc\nWHERE\n (ts BETWEEN $__timeFrom() AND $__timeTo()) AND \n  node='[[node]]'\nORDER BY ts"
    },
    {
     "rawSql": "SELECT\n  $__time(ts),\n  temp\nFROM\n  ertsalloc\nWHERE\n (ts BETWEEN $__timeFrom() AND $__timeTo()) AND \n  node='[[node]]'\nORDER BY ts"
    },
    {
     "rawSql": "SELECT\n  $__time(ts),\n  fix\nFROM\n  ertsalloc\nWHERE\n (ts BETWEEN $__timeFrom() AND $__timeTo()) AND \n  node='[[node]]'\nORDER BY ts"
    },
    {
     "rawSql": "SELECT\n  $__time(ts),\n  std\nFROM\n  ertsalloc\nWHERE\n (ts BETWEEN $__timeFrom() AND $__timeTo()) AND \n  node='[[node]]'\nORDER BY ts"
    }
   ]
  },
  {
   "title": "Allocated Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(ts),\n  allocated\nFROM\n  memory\nWHERE\n (ts BETWEEN $__timeFrom() AND $__timeTo()) AND \n  node='[[node]]'\nORDER BY ts"
    },
    {},
    {
     "rawSql": "SELECT\n  $__time(ts),\n  used\nFROM\n  memory\nWHERE\n (ts BETWEEN $__timeFrom() AND $__timeTo()) AND \n  node='[[node]]'\nORDER BY ts"
    }
   ]
  }
 ]
}