name: Build
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - master
jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        otp-version: [23, 24, 25, 26]
    runs-on: ${{ matrix.platform }}
    container:
      image: erlang:${{ matrix.otp-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache Dialyzer PLTs
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/rebar3/rebar3_*_plt
            _build/**/*_plt
          key: ${{ runner.os }}-otp${{ matrix.otp-version }}-dialyzer-${{ hashFiles('rebar.config') }}
          restore-keys: |
            ${{ runner.os }}-otp${{ matrix.otp-version }}-dialyzer-

      - name: Compile
        run: rebar3 do compile

      - name: Analyze
        run: rebar3 do xref, dialyzer

      - name: Test
        run: rebar3 do eunit, ct
