name: Build
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-20.04
    name: Erlang/OTP ${{matrix.otp}}
    strategy:
      matrix:
        otp:
          - '25'
          - '24'
          - '23'
        rebar3:
          - '3'
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          rebar3-version: ${{matrix.rebar3}}

      - name: Compile
        run: rebar3 do compile

      - name: Analyze
        run: rebar3 do xref, dialyzer

      - name: Test
        run: rebar3 do eunit, ct
